repositories:
  remote:
   - https://stocksoftware.jfrog.io/stocksoftware/maven2
   - https://repo.maven.apache.org/maven2

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.14

  javaee_api: javax:javaee-api:jar:8.0
  javax_annotations: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1
