repositories:
  remote:
   - https://repo1.maven.org/maven2

artifacts:
  javaee_api: javax:javaee-api:jar:7.0
  jsr305_annotations: org.realityforge.javax.annotation:javax.annotation:jar:1.0.0
  keycloak_core: org.keycloak:keycloak-core:jar:2.0.0.Final
  keycloak_common: org.keycloak:keycloak-common:jar:2.0.0.Final
  keycloak_adapter_core: org.keycloak:keycloak-adapter-core:jar:2.0.0.Final
  keycloak_adapter_spi: org.keycloak:keycloak-adapter-spi:jar:2.0.0.Final
  glassfish_embedded: fish.payara.extras:payara-embedded-all:jar:4.1.1.171.1
